-- commento monorigo (lo spazione deve esserci)
# commento monoriga
/*
commento multiriga
*/

# RICORDATEVI SEMPRE CHE E' IL SEMPRE AD AVERE RAGIONE, NON LO SCRIPT

# creazione di un database chiamato PrimoDataBase
CREATE DATABASE DB112;

# SQL non è casesensitive
# LA CONVENZIONE PERO' CI DICE DI SCRIVERE IN CAPS LE PAROLE CHE SONO COAMANDI

#IN SQL NON BASTA SCRIVERE LO SCRIPT, MA VA LANCIATO AFFINCHE' SIA ESEGUITO RELAMENTE DAL SERVER
#ATTENZIONE! DOPO LANCIATO COMMANDO, E' MOLTO MOLTO DIFFICILE TORNARE IN INDIETRO

#UNA VOLTA ESEGUITO LO SCRIPT, PER SQL QUELLO SCRIPT NON HA PIU VALORE.

#PER ESEGUIRE UNO SCRIPT SI DEVE EVIDENZIARE TUTTO IL COMANDO, FINO AL ; E CLICCARE SUL FULMINE "LIBERO"

# usa il database DB112
USE DB112;

# CREARE LA TABELLA PERSONE
CREATE TABLE Persone
(
	nome VARCHAR(60),
    cognome VARCHAR(80),
    citta_residenza VARCHAR(50),
    dob DATE,
    stipendio DOUBLE,
    #stipendio2 DECIMAL(7,2),
    numero_civico INT,
    sposato BOOL
);
ALTER TABLE Persone
DROP COLUMN stipendio2;
# 1 E' TRUE AND 0 E' FALSE